version: '3.8'

services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db    
    # container_name: mongodb   
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: max
    #   MONGO_INITDB_ROOT_PASSWORD: secret
      # - MONGO_USER=max
    env_file:
      - ./env/mongo.env
    

  backend:
    build: ./backend
    # image: node    
      # context: ./backend
      # dockerfile: Dockerfile
      # args:
      #   HOST_NAME: qualquercoisa
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '8001:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/mongo.env
    depends_on:
      - mongodb
    

  frontend:
    build: ./frontend    
    volumes:
      - ./frontend/src:/app/src
      - frontend:/app/node_modules
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    depends_on:      
      - backend
    


volumes:
  data:
  logs:
  frontend:

# networks:
#   mvc: