services:                              
  image: mariadb
  volumes:
    - /home/ramos/Desktop/docker/jdbcbanco:/var/lib/mysql   
  ports:
    - "3306:3306"                         
  restart: always                         
  environment:
    MYSQL_ROOT_PASSWORD: ${SQL_PASSWD}
    MYSQL_DATABASE: ${SQL_DATABASE}
    MYSQL_USER: ${SQL_USER}
    MYSQL_PASSWORD: ${SQL_PASSWORD}
