version: '3.8'

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /c/tmp/banco2:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWD}
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
