version: '3.9'      

services:
  nginx:                                    
    image: nginx
    volumes:
      - /c/tmp/fiscalizacao2:/usr/share/nginx/html
    restart: always    
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80    