Vagrant.configure("2") do |config|
  (1..4).each do |i|
    config.vm.define "graylog_#{i}" do |mongo|
      mongo.vm.box = "centos/7"
      mongo.vm.network "public_network", bridge: "enp12s0"
    end
  end
end
