Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", bridge: "wlp0s20f3", type: "dhcp"
# config.disksize.size = "55GB"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
    v.name = "openstack-controller"
  end
end
