Vagrant.configure "2" do |config|
  config.vm.define "walle" do |walle|
    walle.vm.box= "ubuntu/focal64"
    walle.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.0.12", hostname: "true"
    walle.vm.hostname= "wall-e"
  end
end
