Vagrant.configure("2") do |config|
  config.vm.define "teste3" do |teste2|
    teste2.vm.box = "ubuntu/focal64"
    teste2.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.0.6"
  end
end 
